name: face_sdk_3divi
description: Face SDK plugin
version: 1.0.0
homepage: https://3divi.ai/
repository: https://github.com/3DiVi/face-sdk

environment:
  sdk: ">=2.17.0 <=3.2.3"
  flutter: ">=3.3.0"

dependencies:
  path: ^1.8.3
  path_provider: ^2.0.0
  ffi: ^1.0.0
  xml: ^6.0.0
  camera: ^0.10.1
  image: ^3.2.2
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.face_sdk_3divi
        pluginClass: FaceSdkPlugin
      ios:
        pluginClass: FaceSdkPlugin

