name: face_sdk_3divi
version: 1.4.0
description: 3DiVi Face SDK plugin. Implements Face Recognition, Face Detection and Face Keypoints Detection.
homepage: https://3divi.ai/
repository: https://github.com/3DiVi/face-sdk

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.11.0
  ffi: ^2.1.3
  image: ^4.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.face_sdk_3divi
        pluginClass: FaceSdkPlugin
      ios:
        pluginClass: FaceSdkPlugin

